language: android
jdk: oraclejdk8


android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository
 

script:
    - ./gradlew build

branches:
  only:
  - master
  - develop
  
