object Libs {
    const val assertjVersion = "3.18.1"
    const val daggerVersion = "2.30.1"
    const val jodaVersion = "2.10.1"
    const val kotlinxSerializationVersion = "1.0-M1-1.4.0-rc"
    const val lifecycleReactiveStreamsVersion = "2.2.0"
    const val recyclerViewVersion = "1.2.0-alpha01"
    const val roomVersion = "2.3.0-alpha02"
    const val rxAndroidVersion = "3.0.0"
    const val rxJavaVersion = "3.0.7"
    const val rxKotlinVersion = "3.0.1"
    const val rxRelayVersion = "3.0.0"
    const val websocketVersion = "1.5.1"
    const val junit5Version = "5.7.0"
    const val kotlinLoggingVersion = "2.0.2"
    const val slf4jVersion = "1.7.21"
}
